// Plan building: repo state in, the complete desired set of generated files
// out. Build is deterministic and side-effect free — sync writes the plan,
// --check diffs it, --dry-run prints it. Merge-style surfaces (MCP configs,
// .gitignore) read the current working-tree file as merge input, which keeps
// generation idempotent: regenerating from a synced tree reproduces it.
package adapters

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"blueprint/internal/retrieval"
)

// File is one planned output, path repo-relative in slash form.
type File struct {
	Path    string
	Content []byte
}

// Plan is the full desired generated set for one repo.
type Plan struct {
	Files []File
}

// Paths returns every planned path in plan order.
func (p *Plan) Paths() []string {
	out := make([]string, len(p.Files))
	for i, f := range p.Files {
		out[i] = f.Path
	}
	return out
}

// provenanceMarker appears in every generated file (in a syntax-appropriate
// comment) and is how sync distinguishes "ours, overwrite freely" from
// "user file, .bak it first".
const provenanceMarker = "generated by blueprint"

// IsGenerated reports whether content carries the provenance marker.
func IsGenerated(content []byte) bool {
	return bytes.Contains(content, []byte(provenanceMarker))
}

// commandStub describes one /blueprint-* command surface.
type commandStub struct {
	name    string // file stem: blueprint-<name>
	title   string
	command string // CLI invocation the stub tells the agent to run
	usage   string // how to consume the --json output
}

var commandStubs = []commandStub{
	{
		name:    "new",
		title:   "Start a new blueprint change",
		command: "blueprint new \"<intent>\" --json",
		usage: "The JSON contains the change `id`, routed `tier`, and the path to `.blueprint/changes/<id>/change.md`.\n" +
			"Open that change.md: fill the EARS Delta (every requirement needs a machine-settleable `verify` method)\n" +
			"and the Tasks checklist before writing any code. The loop contract in the TOML frontmatter is binding.",
	},
	{
		name:    "resume",
		title:   "Resume an in-flight blueprint change",
		command: "blueprint resume <change-id> --json",
		usage: "The JSON is the resume context: current loop state, last journal events, and remaining tasks.\n" +
			"Continue from the first unchecked task. Never restart finished work; the journal is append-only truth.",
	},
	{
		name:    "verify",
		title:   "Verify a blueprint change",
		command: "blueprint verify <change-id> --json",
		usage: "The JSON verdict has `pass`, `tamper`, and per-check results with `detail` remediation text.\n" +
			"If `pass` is false, fix the first failing check's cited requirement and rerun. Completion is never\n" +
			"self-declared: only a passing verdict closes the loop. Never edit verdict files or approved.lock.",
	},
	{
		name:    "status",
		title:   "Show blueprint change status",
		command: "blueprint status --json",
		usage: "The JSON lists every open change with its tier, status, and loop state.\n" +
			"Use it to pick up parked work or report progress; do not infer status from the working tree.",
	},
}

func renderCommandStub(t Target, s commandStub) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- %s %s for %s; edit nothing here — regenerate with `blueprint sync` -->\n", provenanceMarker, GeneratorVersion, t.Name)
	fmt.Fprintf(&b, "# %s\n\n", s.title)
	fmt.Fprintf(&b, "Run:\n\n```sh\n%s\n```\n\n%s\n", s.command, s.usage)
	return []byte(b.String())
}

func renderInstructionShim() []byte {
	return []byte(fmt.Sprintf(
		"<!-- %s %s; edit AGENTS.md instead -->\n@AGENTS.md\n",
		provenanceMarker, GeneratorVersion))
}

// gitignore managed-block markers (same managed-region idea as AGENTS.md).
const (
	gitignoreBegin = "# >>> blueprint:managed — generated adapter surfaces; do not edit inside this block"
	gitignoreEnd   = "# <<< blueprint:managed"
)

// mergeGitignore replaces the managed block in an existing .gitignore (or
// appends one), leaving every user line outside the markers untouched.
func mergeGitignore(existing []byte, generatedPaths []string) []byte {
	paths := append([]string(nil), generatedPaths...)
	// Framework caches ride along in the managed block: map.json is [tool]-tier
	// and hook-refreshed on every commit — tracking it would re-dirty the tree
	// after each commit, forever.
	paths = append(paths, ".blueprint/map.json")
	sort.Strings(paths)
	var block strings.Builder
	block.WriteString(gitignoreBegin + "\n")
	fmt.Fprintf(&block, "# %s %s — regenerable via `blueprint sync`; kept out of history on purpose\n", provenanceMarker, GeneratorVersion)
	for _, p := range paths {
		block.WriteString(p + "\n")
	}
	block.WriteString(gitignoreEnd + "\n")

	content := strings.ReplaceAll(string(existing), "\r\n", "\n")
	begin := strings.Index(content, gitignoreBegin)
	end := strings.Index(content, gitignoreEnd)
	if begin >= 0 && end > begin {
		after := content[end+len(gitignoreEnd):]
		after = strings.TrimPrefix(after, "\n")
		return []byte(content[:begin] + block.String() + after)
	}
	if content != "" && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	if content != "" {
		content += "\n"
	}
	return []byte(content + block.String())
}

// Build computes the full desired plan from the repo's current state.
func Build(repoRoot string) (*Plan, error) {
	plan := &Plan{}
	add := func(path string, content []byte) {
		plan.Files = append(plan.Files, File{Path: path, Content: content})
	}

	rules, err := LoadSteering(repoRoot)
	if err != nil {
		return nil, err
	}
	servers, err := LoadMCPServers(repoRoot)
	if err != nil {
		return nil, err
	}
	// Tier-2 retrieval wiring (DESIGN §9): non-empty [retrieval] tier2_*
	// values add blueprint-owned MCP server entries to the same map the
	// generators consume, so every merge/preserve guarantee applies
	// unchanged. An explicit [mcp.servers.<name>] with the same name wins —
	// user declarations outrank the built-in table.
	rcfg, err := retrieval.Load(repoRoot)
	if err != nil {
		return nil, fmt.Errorf("adapters: %w", err)
	}
	tier2, err := retrieval.Tier2Tools(rcfg)
	if err != nil {
		return nil, fmt.Errorf("adapters: %w", err)
	}
	if len(tier2) > 0 && servers == nil {
		servers = map[string]MCPServer{}
	}
	for name, tool := range tier2 {
		if _, declared := servers[name]; declared {
			continue
		}
		servers[name] = MCPServer{Command: tool.Command, Args: tool.Args}
	}

	// Safety compile (DESIGN §13): [deny].write globs -> Claude Code
	// permission deny rules, merged into any existing settings.json. The
	// Codex and Cursor safety surfaces are emitted per-target below.
	denyGlobs, err := LoadDenyGlobs(repoRoot)
	if err != nil {
		return nil, err
	}
	if len(denyGlobs) > 0 {
		const settingsPath = ".claude/settings.json"
		existing, rerr := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(settingsPath)))
		if rerr != nil && !os.IsNotExist(rerr) {
			return nil, fmt.Errorf("adapters: cannot read %s: %w", settingsPath, rerr)
		}
		merged, merr := MergeClaudeSettings(existing, denyGlobs)
		if merr != nil {
			return nil, merr
		}
		add(settingsPath, merged)
	}

	for _, t := range Targets() {
		// Safety compile, non-Claude surfaces: Codex gets the sandbox
		// policy doc (its config-fragment guidance block merges in the
		// MCP branch below); Cursor gets the non-parity note. Both state
		// explicitly that deny globs are NOT host-enforced there — the
		// verify-side tamper layer is the backstop.
		if len(denyGlobs) > 0 {
			switch t.Name {
			case "codex":
				if t.MCPConfigPath != "" {
					add(CodexSandboxPolicyPath, RenderCodexSandboxPolicy(denyGlobs))
				}
			case "cursor":
				add(CursorSafetyNotePath, RenderCursorSafetyNote(denyGlobs))
			}
		}
		if t.InstructionPath != "" {
			add(t.InstructionPath, renderInstructionShim())
		}
		if t.CommandsDir != "" {
			ext := t.CommandsExt
			if ext == "" {
				ext = ".md"
			}
			for _, s := range commandStubs {
				var content []byte
				if t.CommandsFormat == CommandsTOML {
					content = renderCommandTOML(t, s)
				} else {
					content = renderCommandStub(t, s)
				}
				add(t.CommandsDir+"/blueprint-"+s.name+ext, content)
			}
		}
		if t.RulesDir != "" {
			for _, r := range rules {
				for _, f := range RenderRuleFiles(t, r) {
					add(f.Path, f.Content)
					// Mirror dirs get byte-identical copies (a tool
					// mid-migration reads either path; AC-4b zero-loss
					// holds because both are generated from one source).
					for _, mir := range t.RulesMirrorDirs {
						add(mir+strings.TrimPrefix(f.Path, t.RulesDir), f.Content)
					}
				}
			}
		}
		// MCP note targets have no generatable config surface: emit the
		// documented-unknown/unsupported note when servers are declared.
		if t.MCPNotePath != "" && len(servers) > 0 {
			add(t.MCPNotePath, RenderMCPNote(t, servers))
		}
		// The codex config fragment is generated when there are servers to
		// project OR safety guidance to merge; gemini settings always (the
		// context.fileName key is its instruction wiring, servers or not);
		// other targets only when servers exist.
		codexSafety := t.Name == "codex" && len(denyGlobs) > 0
		geminiAlways := t.MCPFormat == MCPFormatGeminiSettings
		if t.MCPConfigPath != "" && (len(servers) > 0 || codexSafety || geminiAlways) {
			existing, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(t.MCPConfigPath)))
			if err != nil && !os.IsNotExist(err) {
				return nil, fmt.Errorf("adapters: cannot read %s: %w", t.MCPConfigPath, err)
			}
			var merged []byte
			switch t.MCPFormat {
			case MCPFormatTOML:
				var globs []string
				if codexSafety {
					globs = denyGlobs
				}
				merged, err = MergeCodexConfig(existing, servers, globs)
			case MCPFormatGeminiSettings:
				merged, err = MergeGeminiSettings(existing, servers)
			default:
				merged, err = MergeMCPJSON(existing, servers)
			}
			if err != nil {
				return nil, fmt.Errorf("adapters: %s: %w", t.MCPConfigPath, err)
			}
			add(t.MCPConfigPath, merged)
		}
	}

	// .gitignore lists every generated path so adapter output stays out of
	// history; the managed block is merged, not overwritten.
	existingIgnore, err := os.ReadFile(filepath.Join(repoRoot, ".gitignore"))
	if err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("adapters: cannot read .gitignore: %w", err)
	}
	add(".gitignore", mergeGitignore(existingIgnore, plan.Paths()))
	return plan, nil
}
