// MCP config generation: the [mcp.servers.<name>] tables in
// .blueprint/config.toml are projected into each tool's native MCP file.
// MERGE, never overwrite: existing files are parsed and every entry we did not
// declare is preserved byte-for-byte in value terms — blueprint owns only the
// server entries named in config.toml.
package adapters

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

// MCPServer is one server declaration from .blueprint/config.toml.
type MCPServer struct {
	Command string            `toml:"command" json:"command"`
	Args    []string          `toml:"args" json:"args,omitempty"`
	Env     map[string]string `toml:"env" json:"env,omitempty"`
}

type mcpFileConfig struct {
	MCP struct {
		Servers map[string]MCPServer `toml:"servers"`
	} `toml:"mcp"`
}

// LoadMCPServers reads the [mcp.servers] table; a missing config.toml or
// absent table means no MCP surfaces are generated. Unknown keys in
// config.toml belong to other features and are ignored.
func LoadMCPServers(repoRoot string) (map[string]MCPServer, error) {
	p := filepath.Join(repoRoot, ".blueprint", "config.toml")
	raw, err := os.ReadFile(p)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("adapters: cannot read %s: %w", p, err)
	}
	var cfg mcpFileConfig
	if err := toml.Unmarshal(raw, &cfg); err != nil {
		return nil, fmt.Errorf("adapters: %s is not valid TOML (%v) — fix it before `blueprint sync` can project MCP configs", p, err)
	}
	return cfg.MCP.Servers, nil
}

func sortedNames(servers map[string]MCPServer) []string {
	names := make([]string, 0, len(servers))
	for n := range servers {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// MergeMCPJSON merges the declared servers into an existing {"mcpServers": {}}
// JSON document (existing may be nil for a fresh file). Foreign top-level keys
// and foreign server entries survive untouched. JSON has no comment syntax, so
// provenance rides in a "//" key — the closest JSON-appropriate header.
func MergeMCPJSON(existing []byte, servers map[string]MCPServer) ([]byte, error) {
	doc := map[string]any{}
	if len(bytes.TrimSpace(existing)) > 0 {
		if err := json.Unmarshal(existing, &doc); err != nil {
			return nil, fmt.Errorf("existing MCP config is not valid JSON (%v) — fix or delete it, then rerun `blueprint sync`", err)
		}
	}
	var entries map[string]any
	if cur, ok := doc["mcpServers"].(map[string]any); ok {
		entries = cur
	} else {
		entries = map[string]any{}
	}
	for name, s := range servers {
		entry := map[string]any{"command": s.Command}
		if len(s.Args) > 0 {
			entry["args"] = s.Args
		}
		if len(s.Env) > 0 {
			entry["env"] = s.Env
		}
		entries[name] = entry
	}
	doc["mcpServers"] = entries
	doc["//"] = fmt.Sprintf("MCP entries %s generated by blueprint %s from .blueprint/config.toml [mcp.servers]; other entries are yours — edit the source, then run `blueprint sync`",
		strings.Join(sortedNames(servers), ", "), GeneratorVersion)
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

// MergeMCPTOML merges the declared servers into a codex config.toml fragment
// as [mcp_servers.<name>] tables. Existing foreign keys and foreign
// mcp_servers entries are preserved (values, not comments: the file is
// re-encoded, and the pre-sync original is kept as a .bak). It is the
// servers-only view of MergeCodexConfig (sandbox.go), which additionally
// merges the [sandbox_workspace_write] safety guidance block.
func MergeMCPTOML(existing []byte, servers map[string]MCPServer) ([]byte, error) {
	return MergeCodexConfig(existing, servers, nil)
}
