// Steering transform: .blueprint/steering/*.md (neutral YAML frontmatter:
// id, description, globs, activation) becomes per-tool rule files. Bodies are
// byte-identical across targets — only the frontmatter is rewritten — so a
// rule reads the same no matter which harness loads it.
package adapters

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// SteeringRule is one parsed .blueprint/steering/*.md file.
type SteeringRule struct {
	ID          string   `yaml:"id"`
	Description string   `yaml:"description"`
	Globs       []string `yaml:"globs"`
	Activation  string   `yaml:"activation"` // always | glob | manual
	Body        string   `yaml:"-"`          // markdown after frontmatter, verbatim
	Source      string   `yaml:"-"`          // repo-relative source path (slash form)
}

// steeringFrontmatter tolerates globs given as a single string.
type steeringFrontmatter struct {
	ID          string `yaml:"id"`
	Description string `yaml:"description"`
	Globs       any    `yaml:"globs"`
	Activation  string `yaml:"activation"`
}

// LoadSteering parses every *.md under .blueprint/steering, sorted by file
// name for deterministic output. A missing directory means no rules.
func LoadSteering(repoRoot string) ([]SteeringRule, error) {
	dir := filepath.Join(repoRoot, ".blueprint", "steering")
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("adapters: cannot read steering dir %s: %w", dir, err)
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	var rules []SteeringRule
	for _, name := range names {
		p := filepath.Join(dir, name)
		raw, err := os.ReadFile(p)
		if err != nil {
			return nil, fmt.Errorf("adapters: cannot read steering file %s: %w", p, err)
		}
		rule, err := parseSteering(raw)
		if err != nil {
			return nil, fmt.Errorf("adapters: %s: %v — steering files need `---` YAML frontmatter with id, description, globs, activation, then a markdown body", p, err)
		}
		if rule.ID == "" {
			base := strings.TrimSuffix(name, ".md")
			rule.ID = base
		}
		rule.Source = ".blueprint/steering/" + name
		rules = append(rules, rule)
	}
	return rules, nil
}

func parseSteering(raw []byte) (SteeringRule, error) {
	var rule SteeringRule
	content := bytes.ReplaceAll(raw, []byte("\r\n"), []byte("\n"))
	if !bytes.HasPrefix(content, []byte("---\n")) {
		return rule, fmt.Errorf("missing YAML frontmatter opener `---`")
	}
	rest := content[4:]
	end := bytes.Index(rest, []byte("\n---"))
	if end < 0 {
		return rule, fmt.Errorf("unterminated YAML frontmatter (no closing `---`)")
	}
	var fm steeringFrontmatter
	if err := yaml.Unmarshal(rest[:end+1], &fm); err != nil {
		return rule, fmt.Errorf("frontmatter is not valid YAML: %v", err)
	}
	body := rest[end+4:] // past "\n---"
	body = bytes.TrimPrefix(body, []byte("\n"))
	rule.ID = fm.ID
	rule.Description = fm.Description
	rule.Activation = fm.Activation
	rule.Globs = normalizeGlobs(fm.Globs)
	rule.Body = string(body)
	return rule, nil
}

func normalizeGlobs(v any) []string {
	switch g := v.(type) {
	case string:
		if g == "" {
			return nil
		}
		return []string{g}
	case []any:
		var out []string
		for _, item := range g {
			if s, ok := item.(string); ok && s != "" {
				out = append(out, s)
			}
		}
		return out
	}
	return nil
}

// RenderRule produces the target rule file for one steering rule. The body is
// appended verbatim (byte-identical across targets); the provenance line lives
// inside the frontmatter as a YAML comment so it never touches the body.
func RenderRule(t Target, r SteeringRule) []byte {
	var b strings.Builder
	b.WriteString(renderRuleFrontmatter(t, r, ""))
	b.WriteString(r.Body)
	return []byte(b.String())
}

// renderRuleFrontmatter renders the per-target frontmatter block. A non-empty
// note (the oversize-split provenance) is inserted as an extra YAML comment so
// it never leaks into the body.
func renderRuleFrontmatter(t Target, r SteeringRule, note string) string {
	var b strings.Builder
	prov := fmt.Sprintf("# generated by blueprint %s from %s; edit the source, then run `blueprint sync`", GeneratorVersion, r.Source)
	b.WriteString("---\n")
	b.WriteString(prov + "\n")
	if note != "" {
		b.WriteString("# " + note + "\n")
	}
	switch t.RulesTransform {
	case TransformMDC:
		b.WriteString("description: " + yamlScalar(r.Description) + "\n")
		b.WriteString("globs: " + yamlFlowList(r.Globs) + "\n")
		if r.Activation == "always" {
			b.WriteString("alwaysApply: true\n")
		} else {
			b.WriteString("alwaysApply: false\n")
		}
	case TransformWindsurf:
		// Windsurf vocabulary (research D7 §5): trigger is always_on /
		// glob (+globs) / manual / model_decision. The neutral activation
		// set maps 1:1 except model_decision, which blueprint never emits.
		switch r.Activation {
		case "glob":
			b.WriteString("trigger: glob\n")
			b.WriteString("globs: " + yamlFlowList(r.Globs) + "\n")
		case "manual":
			b.WriteString("trigger: manual\n")
		default:
			b.WriteString("trigger: always_on\n")
		}
		b.WriteString("description: " + yamlScalar(r.Description) + "\n")
	case TransformApplyTo:
		// Copilot vocabulary (research D7 §4): applyTo is a comma-joined
		// glob string; "**" means always. Manual rules get no applyTo —
		// they are reference-only, which is the closest Copilot has.
		b.WriteString("description: " + yamlScalar(r.Description) + "\n")
		switch r.Activation {
		case "glob":
			b.WriteString("applyTo: " + yamlScalar(strings.Join(r.Globs, ",")) + "\n")
		case "manual":
			// no applyTo: not auto-attached anywhere
		default:
			b.WriteString("applyTo: " + yamlScalar("**") + "\n")
		}
	default: // TransformCopy: neutral frontmatter, keys as authored
		b.WriteString("id: " + yamlScalar(r.ID) + "\n")
		b.WriteString("description: " + yamlScalar(r.Description) + "\n")
		b.WriteString("globs: " + yamlFlowList(r.Globs) + "\n")
		b.WriteString("activation: " + yamlScalar(r.Activation) + "\n")
	}
	b.WriteString("---\n")
	return b.String()
}

// RenderRuleFiles renders one steering rule into the target's rules dir,
// splitting the body across numbered part files when the whole rendered file
// would exceed t.RuleByteBudget (the generator lint for hosts with per-rule
// caps, e.g. Windsurf's 12,000 chars — a byte cap >= a char cap in UTF-8).
// Part bodies concatenate byte-exactly to the canonical body, and every part
// carries a split provenance note in its frontmatter.
func RenderRuleFiles(t Target, r SteeringRule) []File {
	whole := RenderRule(t, r)
	if t.RuleByteBudget <= 0 || len(whole) <= t.RuleByteBudget {
		return []File{{Path: t.RulesDir + "/" + r.ID + t.RulesExt, Content: whole}}
	}
	// Reserve frontmatter overhead using the widest realistic note, then
	// split the body at line boundaries into chunks that fit beside it.
	partNote := func(i, n int) string {
		return fmt.Sprintf("part %d of %d — split by blueprint: %s caps each rule file at %d bytes; the parts concatenate to the canonical body in %s", i, n, t.Name, t.RuleByteBudget, r.Source)
	}
	overhead := len(renderRuleFrontmatter(t, r, partNote(999, 999)))
	chunks := splitAtLines(r.Body, t.RuleByteBudget-overhead)
	files := make([]File, 0, len(chunks))
	for i, chunk := range chunks {
		fm := renderRuleFrontmatter(t, r, partNote(i+1, len(chunks)))
		files = append(files, File{
			Path:    fmt.Sprintf("%s/%s-part%d%s", t.RulesDir, r.ID, i+1, t.RulesExt),
			Content: []byte(fm + chunk),
		})
	}
	return files
}

// splitAtLines cuts s into chunks of at most max bytes, preferring line
// boundaries; a single line longer than max is hard-split. Concatenating the
// chunks reproduces s byte-exactly.
func splitAtLines(s string, max int) []string {
	if max < 1 {
		max = 1
	}
	var chunks []string
	var cur strings.Builder
	flush := func() {
		if cur.Len() > 0 {
			chunks = append(chunks, cur.String())
			cur.Reset()
		}
	}
	for len(s) > 0 {
		nl := strings.IndexByte(s, '\n')
		var line string
		if nl < 0 {
			line, s = s, ""
		} else {
			line, s = s[:nl+1], s[nl+1:]
		}
		for len(line) > max {
			flush()
			chunks = append(chunks, line[:max])
			line = line[max:]
		}
		if cur.Len()+len(line) > max {
			flush()
		}
		cur.WriteString(line)
	}
	flush()
	return chunks
}

// yamlScalar quotes a scalar only when needed, keeping output diff-friendly.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ":#{}[]&*!|>'\"%@`,\n") {
		q, _ := yaml.Marshal(s)
		return strings.TrimSuffix(string(q), "\n")
	}
	return s
}

func yamlFlowList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = yamlScalar(it)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
